<?php
// autoload.php @generated by Composer
function ext_autoload($className) {
    $arr = explode('\\',$className);
    
    var_dump($arr);
    
    if($arr[0] == 'Ext'){
        $path = implode(DIRECTORY_SEPARATOR,array_slice($arr,1));
        $file = __DIR__ .'/'. $path . '.php';

//         var_dump($file);

        if (file_exists($file)) require_once $file;
    }
}
spl_autoload_register('ext_autoload');
